# Generated by Django 3.2.6 on 2021-11-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
    ]
