# Generated by Django 3.2.6 on 2021-11-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_alter_location_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='locations',
        ),
    ]
